# Alias
man: fzf_man-db
sib: scoop_install_local

# Bin
## choco
ch: choco info
cs: choco search
ci: gsudo choco install -y
cu: gsudo choco uninstall
cup: gsudo choco upgrade
cua: gsudo choco upgrade all -y
cl: choco list
## scoop
ss: scoop search
si: scoop install
su: scoop uninstall
rsi: scoop install $1 && scoop uninstall $1
sh: scoop home
sl: scoop list
sst: scoop status
sup: scoop update
sua: scoop update -a -k
sca: scoop cleanup * && scoop cache rm *
fcc: scoop_formatjson $1 && scoop_checkver $1 && scoop_checkhashes $1

# Opt
# Directory Opus
do: dopus "%CD%\$*"
# e: explorer %CD%\$*
reader: mprocs "bash start_openreader-webui.sh" "bash start_kokoro-fastapi.sh"

# Shell
_neovide: bash _neovide.sh
nv: _nvim
git_init: bash git_init.sh
git_push: bash git_push.sh
git_tag: bash git_tag.sh
magick_annot: bash magick_annot.sh
magick_gen: bash magick_gen.sh
magick_gird: bash magick_gird.sh
magick_halftone: bash magick_halftone.sh
